### ISSUE TITLE
Container for jedi-edu

### ISSUE THREAD

**Issue by cmgas** [JCSDA-internal/jedi-edu#1]
@cmgas commented on [Wed Aug 10 2022](https://github.com/JCSDA-internal/jedi-docs/issues/479)

To move to jedi-edu repo

The container (built with spack?) needs to have: 
- basic environment needed for JEDI
- built code from sept JEDI release (oops-bundle only)
- notebooks with tutorial
- no data needed

**Comment by mer-a-o** [comment]
@cmgas I think it makes more sense to keep the notebooks in jedi-edu rather than container. Hosting them in the repo makes edits/updates easier. We can tag jedi-edu repo once the tutorials are finalized.  If you are ok with this suggestion please close this issue. The EDU container is now available on dockerhub. See this for details: https://github.com/JCSDA-internal/jedi-edu/pull/3
